//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingFruits
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fruit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fruit()
        {
            this.Inventories = new HashSet<Inventory>();
        }
    
        public int Fruit_ID { get; set; }
        public string Fruit_Name { get; set; }
        public Nullable<decimal> Fruit_Price { get; set; }
        public Nullable<int> Fruit_Barcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventories { get; set; }
    }
}
