//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingFruits
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int Inventory_ID { get; set; }
        public string Inventory_Name { get; set; }
        public Nullable<int> Fruit_ID { get; set; }
        public Nullable<int> Usr_ID { get; set; }
    
        public virtual Fruit Fruit { get; set; }
        public virtual UserDeatil UserDeatil { get; set; }
    }
}
