//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmingFruits
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FarmingFruitsEntities2 : DbContext
    {
        public FarmingFruitsEntities2()
            : base("name=FarmingFruitsEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fruit> Fruits { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<UserDeatil> UserDeatils { get; set; }
    }
}
